name: Lint Code Base

on:
  - pull_request_target

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          submodules: 'true'
          fetch-depth: 0
      - run: |
          git fetch --no-tags --prune origin

      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          # RUBY_CONFIG_FILE: ./pronto/rubocop/rubocop.yml
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
